// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/DotCaffeineRoot/SubAwesome/index.js

(module.exports = require('./namespace'))

.addModules({
  BetaRelease: require('./BetaRelease')
});