# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/DotCaffeineRoot/SubAwesome/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BetaRelease: require './BetaRelease'