// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/DotCaffeineRoot/SubAwesome/namespace.js

module.exports = require('../namespace').addNamespace(
  'SubAwesome',
  class SubAwesome extends Neptune.PackageNamespace {}
);
