# generated by Neptune Namespaces v2.x.x
# file: files/SourceRoots/DotCaffeineRoot/SubAwesome/namespace.coffee

DotCaffeineRoot = require '../namespace'
module.exports = DotCaffeineRoot.SubAwesome ||
DotCaffeineRoot.addNamespace 'SubAwesome', class SubAwesome extends Neptune.Base
  ;
