# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/DotCaffeineRoot/SubAwesome/namespace.coffee

module.exports = (require '../namespace').addNamespace('SubAwesome', class SubAwesome extends Neptune.PackageNamespace)
