# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineMc/index.coffee

module.exports = require './namespace'
.addModules
  CaffeineMcParser:     require './CaffeineMcParser'    
  CaffeineMcTestHelper: require './CaffeineMcTestHelper'
  FileCompiler:         require './FileCompiler'        
  MetaCompiler:         require './MetaCompiler'        
  ModuleResolver:       require './ModuleResolver'      
  SourceRoots:          require './SourceRoots'         