// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineMc/index.js

(module.exports = require('./namespace'))

.addModules({
  CaffeineMcParser:     require('./CaffeineMcParser'),
  CaffeineMcTestHelper: require('./CaffeineMcTestHelper'),
  CompileCache:         require('./CompileCache'),
  FileCompiler:         require('./FileCompiler'),
  Metacompiler:         require('./Metacompiler'),
  ModuleResolver:       require('./ModuleResolver'),
  SourceRoots:          require('./SourceRoots')
});