# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineMc/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CaffeineMcParser:     require './CaffeineMcParser'    
  CaffeineMcTestHelper: require './CaffeineMcTestHelper'
  CompileCache:         require './CompileCache'        
  FileCompiler:         require './FileCompiler'        
  Metacompiler:         require './Metacompiler'        
  ModuleResolver:       require './ModuleResolver'      
  SourceRoots:          require './SourceRoots'         