# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineMc/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.CaffeineMc ||
Tests.addNamespace 'CaffeineMc', class CaffeineMc extends Neptune.Base
  ;