// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineMc/namespace.js

module.exports = require('../namespace').addNamespace(
  'CaffeineMc',
  (class CaffeineMc extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
