# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineMc/namespace.coffee

module.exports = (require '../namespace').addNamespace 'CaffeineMc', class CaffeineMc extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
