// Generated by CoffeeScript 1.12.7
(function() {
  var CaffeineEight, CaffeineMc, cafSourceMaps, fs, getEnv, loaderUtils, log, ref;

  fs = require('fs');

  ref = require('art-standard-lib'), log = ref.log, getEnv = ref.getEnv;

  loaderUtils = require('loader-utils');

  CaffeineMc = require('./index');

  CaffeineEight = require('caffeine-eight');


  /*
  TODO: Fix SOURCEMAPS (SBD 2018-07-30 notes)
  'cafSourceMaps' is a temporary hack for testing.
  
  This current code actually works with webpack4/webpack-dev-server3 && Safari,
  but it DOESNT work in Chrome. Chrome seems to actually get the sourcemap correctly,
  but it won't show the original source.
  SO - cafSourceMaps is off by default, but you can turn it on if you want:
  
    > cafSourceMaps=true webpack-dev-server
   */

  cafSourceMaps = getEnv.cafSourceMaps;

  module.exports = function(source) {

    /*
    Compile source file if it's present on file system.
    If it's inline source or just string compilation - than compile source itself.
    (for example, when using inline code in .vue files)
     */
    var compileOptions, e, fileExists, js, out, ref1, ref2, sourceFile, sourceMap;
    if (typeof this.cacheable === "function") {
      this.cacheable();
    }
    sourceFile = loaderUtils.getRemainingRequest(this);
    fileExists = fs.existsSync(sourceFile);
    compileOptions = {
      source: source,
      debug: this.debug,
      sourceRoot: "",
      cache: true,
      inlineMap: !!cafSourceMaps,
      prettier: !cafSourceMaps
    };
    try {
      if (fileExists) {
        ref1 = CaffeineMc.FileCompiler.compileFileSync(sourceFile, compileOptions).compiled, js = ref1.js, sourceMap = ref1.sourceMap;
      } else {
        ref2 = CaffeineMc.compile(source, compileOptions).compiled, js = ref2.js, sourceMap = ref2.sourceMap;
      }
      return this.callback(null, js, sourceMap);
    } catch (error) {
      e = error;
      if (e instanceof CaffeineEight.CaffeineEightCompileError) {
        out = new Error(e.toString());
        out.stack = "";
        throw out;
      } else {
        log.error({
          "CaffeineMc webpack-loader error": e
        });
      }
      throw e;
    }
  };

  module.exports.separable = true;

}).call(this);
