// Generated by CoffeeScript 1.11.1
(function() {
  var CaffeineMc, loaderUtils;

  CaffeineMc = require('./index');

  loaderUtils = require('loader-utils');


  /*
  TODO:
  
  - source maps
  - doesn't load caffeine-mc.config.caf
   */

  module.exports = function(source) {
    var coffeeRequest, e, jsRequest, query, result, sourceMap;
    if (typeof this.cacheable === "function") {
      this.cacheable();
    }
    coffeeRequest = loaderUtils.getRemainingRequest(this);
    jsRequest = loaderUtils.getCurrentRequest(this);
    query = loaderUtils.parseQuery(this.query);
    try {
      result = CaffeineMc.compile(source, {
        literate: query.literate,
        sourceFile: coffeeRequest,
        debug: this.debug
      });
    } catch (error) {
      e = error;
      log.error({
        "CaffeineMc error": e
      });
      throw e;
    }
    sourceMap = null;
    return this.callback(null, result.compiled.js, sourceMap);
  };

  module.exports.seperable = true;

}).call(this);
