# generated by Neptune Namespaces v1.x.x
# file: CaffeineMc/index.coffee

module.exports = require './namespace'
.includeInNamespace require './CaffeineMc'
.addModules
  Register: require './Register'
require './compilers'