# generated by Neptune Namespaces v1.x.x
# file: CaffeineMc/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.CaffeineMc ||
Neptune.addNamespace 'CaffeineMc', class CaffeineMc extends Neptune.Base
  ;