# generated by Neptune Namespaces v1.x.x
# file: files/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Files ||
Neptune.addNamespace 'Files', class Files extends Neptune.Base
  ;