# generated by Neptune Namespaces v2.x.x
# file: files/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Files ||
Neptune.addNamespace 'Files', class Files extends Neptune.Base
  ;
require './SourceRoots/namespace'