// generated by Neptune Namespaces v4.x.x
// file: files/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Files',
  (class Files extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./SourceRoots/namespace');