# generated by Neptune Namespaces v3.x.x
# file: files/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Files', class Files extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './SourceRoots/namespace'