// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/DotCaffeineRoot/index.js

(module.exports = require('./namespace'))

.addModules({
  CaffeineMcConfig: require('./caffeine-mc.config'),
  HurlockAlpha:     require('./HurlockAlpha')
});
require('./SubAwesome');