# generated by Neptune Namespaces v1.x.x
# file: files/SourceRoots/DotCaffeineRoot/index.coffee

module.exports = require './namespace'
.addModules
  A:                require './a'                 
  CaffeineMcConfig: require './caffeine-mc.config'
require './subdir'