# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/DotCaffeineRoot/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CaffeineMcConfig: require './caffeine-mc.config'
  HurlockAlpha:     require './HurlockAlpha'      
require './SubAwesome'