# generated by Neptune Namespaces v1.x.x
# file: files/SourceRoots/DotCaffeineRoot/namespace.coffee

SourceRoots = require '../namespace'
module.exports = SourceRoots.DotCaffeineRoot ||
SourceRoots.addNamespace 'DotCaffeineRoot', class DotCaffeineRoot extends Neptune.Base
  ;