# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/DotCaffeineRoot/namespace.coffee

module.exports = (require '../namespace').addNamespace('DotCaffeineRoot', class DotCaffeineRoot extends Neptune.PackageNamespace)
require './SubAwesome/namespace'