// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/DotCaffeineRoot/namespace.js

module.exports = require('../namespace').addNamespace(
  'DotCaffeineRoot',
  class DotCaffeineRoot extends Neptune.PackageNamespace {}
);
require('./SubAwesome/namespace');