# generated by Neptune Namespaces v1.x.x
# file: files/SourceRoots/DotCaffeineRoot/subdir/namespace.coffee

DotCaffeineRoot = require '../namespace'
module.exports = DotCaffeineRoot.Subdir ||
DotCaffeineRoot.addNamespace 'Subdir', class Subdir extends Neptune.Base
  ;