// generated by Neptune Namespaces v4.x.x
// file: CaffeineMc/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CaffeineMc'))
.addModules({
  CaffeineMcParser: require('./CaffeineMcParser'),
  CafRepl:          require('./CafRepl'),
  CompileCache:     require('./CompileCache'),
  DirReader:        require('./DirReader'),
  FileCompiler:     require('./FileCompiler'),
  Highlight:        require('./Highlight'),
  Metacompiler:     require('./Metacompiler'),
  ModuleResolver:   require('./ModuleResolver'),
  Register:         require('./Register'),
  Run:              require('./Run'),
  SourceRoots:      require('./SourceRoots'),
  Tools:            require('./Tools'),
  WorkingCache:     require('./WorkingCache')
});
require('./Compilers');