// generated by Neptune Namespaces v4.x.x
// file: CaffeineMc/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'CaffeineMc',
  (class CaffeineMc extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Compilers/namespace');