# generated by Neptune Namespaces v3.x.x
# file: CaffeineMc/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'CaffeineMc', class CaffeineMc extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Compilers/namespace'