# generated by Neptune Namespaces v0.5
# file: CaffeineMc/compilers/index.coffee

module.exports = require './namespace'
.addModules
  CoffeeScript: require './CoffeeScript'
  JavaScript:   require './JavaScript'
