# generated by Neptune Namespaces v1.x.x
# file: CaffeineMc/compilers/index.coffee

module.exports = require './namespace'
.addModules
  CoffeeScript: require './CoffeeScript'
  JavaScript:   require './JavaScript'  