# generated by Neptune Namespaces v0.5
# file: CaffeineMc/compilers/namespace.coffee

CaffeineMc = require '../namespace'
module.exports = CaffeineMc.Compilers ||
CaffeineMc.addNamespace 'Compilers', class Compilers extends Neptune.Base
  ;