// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/index.js

(module.exports = require('./namespace'))

.addModules({
  DotCaffeineRootPeer: require('./DotCaffeineRootPeer')
});
require('./DotCaffeineRoot');