# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DotCaffeineRootPeer: require './DotCaffeineRootPeer'
require './DotCaffeineRoot'