# generated by Neptune Namespaces v3.x.x
# file: files/SourceRoots/namespace.coffee

module.exports = (require '../namespace').addNamespace('SourceRoots', class SourceRoots extends Neptune.PackageNamespace)
require './DotCaffeineRoot/namespace'