# generated by Neptune Namespaces v2.x.x
# file: files/SourceRoots/namespace.coffee

Files = require '../namespace'
module.exports = Files.SourceRoots ||
Files.addNamespace 'SourceRoots', class SourceRoots extends Neptune.Base
  ;
require './DotCaffeineRoot/namespace'