// generated by Neptune Namespaces v4.x.x
// file: files/SourceRoots/namespace.js

module.exports = require('../namespace').addNamespace(
  'SourceRoots',
  class SourceRoots extends Neptune.PackageNamespace {}
);
require('./DotCaffeineRoot/namespace');