# generated by Neptune Namespaces v1.x.x
# file: files/SourceRoots/namespace.coffee

Files = require '../namespace'
module.exports = Files.SourceRoots ||
Files.addNamespace 'SourceRoots', class SourceRoots extends Neptune.Base
  ;