# generated by Neptune Namespaces v2.x.x
# file: CaffeineMc/Compilers/namespace.coffee

CaffeineMc = require '../namespace'
module.exports = CaffeineMc.Compilers ||
CaffeineMc.addNamespace 'Compilers', class Compilers extends Neptune.Base
  ;
