# generated by Neptune Namespaces v3.x.x
# file: CaffeineMc/Compilers/namespace.coffee

module.exports = (require '../namespace').addNamespace('Compilers', class Compilers extends Neptune.PackageNamespace)
