// generated by Neptune Namespaces v4.x.x
// file: CaffeineMc/Compilers/namespace.js

module.exports = require('../namespace').addNamespace(
  'Compilers',
  class Compilers extends Neptune.PackageNamespace {}
);
